### ISSUE TITLE
q paso con tu numero XDD

### ISSUE THREAD

**Issue by AleXD0009** [Argus628/Bastrap#1]

**Comment by Argus628** [comment]
> **por pendejo te banearon
> 
> > @_XD**_

XDDD no se si sabias pero el jotchua y el bastrap tienen un comando para mandar a soporte a numeros XD y lo use por accidente en el chat privado y me mande a soporte XD y tmb al bastrap XDD

**Comment by Argus628** [comment]
Pasame tu ig asi hablamos xd

**Comment by Argus628** [comment]
Ya te mande soli xd soy ale._2099

**Comment by AleXD0009** [comment]
ok
xdd

**Comment by Argus628** [comment]
Aceptame huevon xd
